#!/bin/bash
# Gives Dokku the ability to support multiple branches for a given service
# Allowing you to have multiple staging environments on a per-branch basis

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

reference_app=$1
refname=$3
newrev=$2
APP=$reference_app

# if app name doesn't contain "test"
if [[ $APP != *"test"* ]]; then
  exit 0
fi

dokku git:set $APP deploy-branch $refname

plugn trigger receive-app $APP $newrev